### ISSUE TITLE
Implement all APIs in library

### ISSUE THREAD

**Issue by mweibel** [rokka-io/rokka-go#6]
Todo still:

- [x] [Add/Delete User metadata on source images](https://rokka.io/documentation/references/image-metadata.html) (#36)
- [x] [Delete sourceimages](https://rokka.io/documentation/references/source-images.html) (#37)
- [x] [Delete source images with binary hash](https://rokka.io/documentation/references/source-images.html) (#37)
- [x] [Download a source image](https://rokka.io/documentation/references/source-images.html) (#37)
- [x] Delete a stack (#38)
